apiVersion: apps/v1
kind: Deployment
metadata:
  name: anthonyposchen-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: anthonyposchen-com
  template:
    metadata:
      labels:
        app.kubernetes.io/name: anthonyposchen-com
    spec:
      containers:
        - name: website
          image: ghcr.io/anthonyposchen/anthonyposchen.com:master-3e447d3-1779335633@sha256:269d776bbd13e76a78428b6c6b61a19f546e40f5c1601904ab921624754764c5 # {"$imagepolicy": "app-anthonyposchen-com:anthonyposchen-com"}
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "42069"
          ports:
            - name: http
              containerPort: 42069
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
