apiVersion: apps/v1
kind: Deployment
metadata:
  name: anthonyposchen-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: anthonyposchen-com
  template:
    metadata:
      labels:
        app.kubernetes.io/name: anthonyposchen-com
    spec:
      containers:
        - name: website
          image: ghcr.io/anthonyposchen/anthonyposchen.com:master-62fc8e8-1779333032@sha256:bed17e4132b2035545ecf6969a14fc475cd5cebf4a2ed4c277c68375ef708362 # {"$imagepolicy": "app-anthonyposchen-com:anthonyposchen-com"}
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "42069"
          ports:
            - name: http
              containerPort: 42069
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
