apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: anthonyposchen-com
  namespace: flux-system
spec:
  image: ghcr.io/anthonyposchen/anthonyposchen.com
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: anthonyposchen-com
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: anthonyposchen-com
  filterTags:
    pattern: "^latest$"
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: anthonyposchen-com
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: app-anthonyposchen-com
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: "chore(images): update anthonyposchen.com image [skip ci]"
    push:
      branch: master
  update:
    path: ./kustomization/base
    strategy: Setters
